markdown: kramdown
kramdown:
    input: GFM
    line_numbers: true 
highlighter: rouge
url: www.deardon.win
lsi: false
safe: true
future: false
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'manage.sh']

excerpt_separator: "<br>"
paginate: 5
paginate_path: "page:num"
# permalink: /:categories/:title.html
# relative_permalinks: true

plugins:
  - jekyll-paginate
  - jekyll-gist

# presonal config
domain: www.deardon.win
title: Don's Blog
description: 学习，记录，交流，分享...
author: Don
email: dpdeng@whu.edu.cn
github: DearDon
base_path: /home/don/Blog

config:
  js_dir:
  img_dir: images
  css_dir:
