markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
permalink: /:categories/:title.html
url: 
lsi: false
safe: true

paginate: 5
paginate_path: "page:num"

gems: [jekyll-paginate]

# presonal config
domain: www.deardon.net
title: Don's Blog
description: 学习，记录，交流，分享...
author: Don
email: dpdeng@whu.edu.cn
github: DearDon

config:
  js_dir:
  img_dir:
  css_dir:
