markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.deardon.net
title: Don's Blog
description: ng...
author: Don
email: dpdeng@whu.edu.cn
github: DearDon

config:
  js_dir:
  img_dir:
  css_dir:
